sever:
 port: 8080

mybatis:
  config-location:  ../mybatis/Ip.xml
spring:
 datasource:
   password: root
   username: root
   url: jdbc:mysql://localhost:3306/test?characterEncoding=utf-8
   driver-class-name: com.mysql.jdbc.Driver
   platform: mysql



